#!/usr/bin/env python3

from __future__ import annotations

import json
import re
from html import escape
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
CONTENT_FILE = ROOT / "content" / "site.json"
TEMPLATE_DIR = ROOT / "templates"
BLOG_DIR = ROOT / "blog"
GENERATED_NOTICE = (
    "<!-- Generated by tools/build_site.py. "
    "Edit content/site.json, posts/*/post.json, or templates/ instead. -->"
)
PLACEHOLDER = re.compile(r"{{\s*([a-zA-Z0-9_]+)\s*}}")


def main() -> None:
    data = json.loads(CONTENT_FILE.read_text(encoding="utf-8"))
    posts = load_posts(data["posts"])
    BLOG_DIR.mkdir(exist_ok=True)
    about_body_root = render_home_body(data["home"], posts, path_prefix="")
    about_body_nested = render_home_body(data["home"], posts, path_prefix="../")

    write_page(
        ROOT / "index.html",
        build_page(
            site=data["site"],
            active_nav="About",
            asset_prefix="",
            page_title=data["home"]["page_title"],
            description=data["home"]["description"],
            body_html=about_body_root,
            footer_html=render_footer(data["site"]["name"], include_copy=True),
        ),
    )

    write_page(
        route_output_path("about"),
        build_page(
            site=data["site"],
            active_nav="About",
            asset_prefix="../",
            page_title=data["home"]["page_title"],
            description=data["home"]["description"],
            body_html=about_body_nested,
            footer_html=render_footer(data["site"]["name"], include_copy=True),
        ),
    )

    write_page(
        route_output_path("blog"),
        build_page(
            site=data["site"],
            active_nav="Blog",
            asset_prefix="../",
            page_title=data["blog"]["page_title"],
            description=data["blog"]["description"],
            body_html=render_template(
                "blog.html",
                {
                    "eyebrow": escape_html(data["blog"]["eyebrow"]),
                    "heading": escape_html(data["blog"]["heading"]),
                    "lead": escape_html(data["blog"]["lead"]),
                    "filter_buttons": indent_block(
                        render_filter_buttons(data["blog"]["filter_order"]),
                        12,
                    ),
                    "post_previews": indent_block(
                        render_post_cards(posts, heading_tag="h2", preview=True, path_prefix="../"),
                        12,
                    ),
                },
            ),
            footer_html=render_footer(data["site"]["name"], include_copy=True),
        ),
    )

    write_page(
        route_output_path("resume"),
        build_page(
            site=data["site"],
            active_nav="Resume",
            asset_prefix="../",
            page_title=data["resume"]["page_title"],
            description=data["resume"]["description"],
            body_html=render_template(
                "resume.html",
                {
                    "eyebrow": escape_html(data["resume"]["eyebrow"]),
                    "heading": escape_html(data["resume"]["heading"]),
                    "lead": escape_html(data["resume"]["lead"]),
                    "resume_links": indent_block(
                        render_links(
                            data["resume"]["links"],
                            default_class="underlined-link",
                        ),
                        12,
                    ),
                    "resume_download_href": escape_attr(
                        f"../{data['resume']['download']['href']}"
                    ),
                    "resume_download_label": escape_html(
                        data["resume"]["download"]["label"]
                    ),
                    "resume_download_filename": escape_attr(
                        data["resume"]["download"]["filename"]
                    ),
                    "education_section": render_resume_section(
                        data["resume"]["education_heading"],
                        render_education_entries(data["resume"]["education"]),
                    ),
                    "skills_section": render_resume_section(
                        data["resume"]["skills_heading"],
                        render_skill_groups(data["resume"]["skills"]),
                    ),
                    "experience_section": render_resume_section(
                        data["resume"]["experience_heading"],
                        render_experience_entries(data["resume"]["experience"]),
                    ),
                    "publications_section": render_resume_section(
                        data["resume"]["publications_heading"],
                        render_publications(data["resume"]["publications"]),
                    ),
                },
            ),
            footer_html=render_footer(data["site"]["name"], include_copy=True),
        ),
    )

    write_page(
        ROOT / "404.html",
        build_page(
            site=data["site"],
            active_nav=None,
            asset_prefix="",
            page_title=data["not_found"]["page_title"],
            description=None,
            body_html=render_template(
                "404.html",
                {
                    "eyebrow": escape_html(data["not_found"]["eyebrow"]),
                    "heading": escape_html(data["not_found"]["heading"]),
                    "body": escape_html(data["not_found"]["body"]),
                    "page_links": indent_block(
                        render_links(data["not_found"]["links"]),
                        12,
                    ),
                },
            ),
            footer_html="",
        ),
    )

    for legacy_path in (ROOT / "blog.html", ROOT / "resume.html"):
        if legacy_path.exists():
            legacy_path.unlink()

    for post in posts:
        legacy_post_path = ROOT / "posts" / f"{post['slug']}.html"
        if legacy_post_path.exists():
            legacy_post_path.unlink()

        post_headings = build_post_headings(post["content"])
        write_page(
            post_output_path(post),
            build_page(
                site=data["site"],
                active_nav="Blog",
                asset_prefix="../../",
                page_title=post["page_title"],
                description=post["description"],
                body_html=render_template(
                    "post.html",
                    {
                        "meta_line": escape_html(post_meta(post)),
                        "heading": escape_html(post["title"]),
                        "toc_html": indent_block(render_post_toc(post_headings), 10),
                        "content_blocks": indent_block(
                            render_post_content(post["content"], post_headings),
                            10,
                        ),
                    },
                ),
                footer_html=render_footer(data["site"]["name"], include_copy=False),
            ),
        )


def build_page(
    *,
    site: dict,
    active_nav: str | None,
    asset_prefix: str,
    page_title: str,
    description: str | None,
    body_html: str,
    footer_html: str,
) -> str:
    return render_template(
        "base.html",
        {
            "generated_notice": GENERATED_NOTICE,
            "page_title": escape_html(page_title),
            "meta_description_tag": render_meta_description(description),
            "asset_prefix": asset_prefix,
            "home_href": f"{asset_prefix}about/",
            "site_name": escape_html(site["name"]),
            "nav_links": indent_block(
                render_nav(site["nav"], active_nav, asset_prefix),
                10,
            ),
            "body_html": body_html,
            "footer_html": footer_html,
        },
    )


def load_posts(post_entries: list[dict]) -> list[dict]:
    posts = []
    for entry in post_entries:
        source = entry.get("source")
        if not source:
            posts.append(entry)
            continue

        post_path = ROOT / source
        post = json.loads(post_path.read_text(encoding="utf-8"))
        if not isinstance(post, dict):
            raise ValueError(f"Post source must contain a JSON object: {post_path}")

        merged_post = dict(post)
        for key, value in entry.items():
            if key != "source":
                merged_post[key] = value
        posts.append(merged_post)

    return posts


def render_template(template_name: str, context: dict[str, str]) -> str:
    template = (TEMPLATE_DIR / template_name).read_text(encoding="utf-8")

    def replace(match: re.Match[str]) -> str:
        key = match.group(1)
        if key not in context:
            raise KeyError(f"Missing template value for {key!r} in {template_name}")
        return context[key]

    return PLACEHOLDER.sub(replace, template)


def render_meta_description(description: str | None) -> str:
    if not description:
        return ""
    return (
        "    <meta\n"
        '      name="description"\n'
        f'      content="{escape_html(description)}"\n'
        "    />"
    )


def render_nav(items: list[dict], active_label: str | None, prefix: str) -> str:
    lines = []
    for item in items:
        attrs = ""
        if item["label"] == active_label:
            attrs = ' aria-current="page"'
        lines.append(
            f'<a href="{escape_attr(prefix + item["href"])}"{attrs}>'
            f"{escape_html(item['label'])}</a>"
        )
    return "\n".join(lines)


def render_links(items: list[dict], default_class: str | None = None) -> str:
    return "\n".join(
        (
            f'<a href="{escape_attr(item["href"])}"'
            f'{render_link_attrs(item, default_class=default_class)}>'
            f"{escape_html(item['label'])}</a>"
        )
        for item in items
    )


def render_link_attrs(item: dict, *, default_class: str | None = None) -> str:
    attrs = []
    class_name = item.get("class_name", default_class)
    if class_name:
        attrs.append(f' class="{escape_attr(class_name)}"')
    if item.get("new_tab"):
        attrs.append(' target="_blank"')
        attrs.append(' rel="noreferrer"')
    return "".join(attrs)


def render_list_items(items: list[str]) -> str:
    return "\n".join(f"<li>{escape_html(item)}</li>" for item in items)


def render_intro_paragraphs(value: str | list[str]) -> str:
    items = [value] if isinstance(value, str) else value
    if not items:
        return ""

    paragraphs = [
        "\n".join(
            [
                '<p class="lead">',
                f"  {escape_html(items[0])}",
                "</p>",
            ]
        )
    ]

    for item in items[1:]:
        paragraphs.append(
            "\n".join(
                [
                    '<p class="intro-body">',
                    f"  {escape_html(item)}",
                    "</p>",
                ]
            )
        )

    return "\n".join(paragraphs)


def render_filter_buttons(tags: list[str]) -> str:
    buttons = ['<button class="filter-chip is-active" type="button" data-filter="all">All</button>']
    for tag in tags:
        buttons.append(
            '<button class="filter-chip" type="button" '
            f'data-filter="{escape_attr(slugify(tag))}">{escape_html(tag)}</button>'
        )
    return "\n".join(buttons)


def render_home_body(home: dict, posts: list[dict], *, path_prefix: str) -> str:
    return render_template(
        "home.html",
        {
            "hero_heading": escape_html(home["hero_heading"]),
            "hero_lead_html": indent_block(
                render_intro_paragraphs(home["hero_lead"]),
                12,
            ),
            "hero_links": indent_block(render_links(home["links"]), 14),
            "focus_heading": escape_html(home["focus_heading"]),
            "focus_body": escape_html(home["focus_body"]),
            "focus_items": indent_block(render_list_items(home["focus_items"]), 12),
            "recent_posts_heading": escape_html(home["recent_posts_heading"]),
            "recent_posts_link_label": escape_html(home["recent_posts_link_label"]),
            "recent_posts_href": escape_attr(f"{path_prefix}blog/"),
            "recent_posts": indent_block(
                render_post_cards(
                    posts[:3],
                    heading_tag="h3",
                    preview=False,
                    path_prefix=path_prefix,
                ),
                12,
            ),
        },
    )


def render_post_cards(
    posts: list[dict], *, heading_tag: str, preview: bool, path_prefix: str = ""
) -> str:
    cards = []
    for post in posts:
        classes = ["post-item"]
        attrs = ""
        if preview:
            classes.append("post-preview")
            attrs = f' data-tags="{escape_attr(" ".join(slugify(tag) for tag in post["tags"]))}"'

        cards.append(
            "\n".join(
                [
                    f'<article class="{" ".join(classes)}"{attrs}>',
                    f"  <{heading_tag}>",
                    f'    <a href="{escape_attr(path_prefix + post_href(post))}">',
                    f"      {escape_html(post['title'])}",
                    "    </a>",
                    f"  </{heading_tag}>",
                    f'  <p class="post-meta">{escape_html(post_meta(post))}</p>',
                    "  <p>",
                    f"    {escape_html(post.get('excerpt', post['lead']))}",
                    "  </p>",
                    "</article>",
                ]
            )
        )
    return "\n".join(cards)


def render_experience_entries(entries: list[dict]) -> str:
    blocks = []
    for entry in entries:
        subtitle = entry["company"]
        if entry.get("location"):
            subtitle = f"{subtitle} - {entry['location']}"
        blocks.append(
            "\n".join(
                [
                    '<div class="resume-entry">',
                    '  <div class="entry-header">',
                    f"    <h3>{escape_html(entry['title'])}</h3>",
                    f'    <p class="post-meta">{escape_html(entry["years"])}</p>',
                    "  </div>",
                    f'  <p class="entry-subtitle">{escape_html(subtitle)}</p>',
                    '  <ul class="simple-list">',
                    indent_block(render_list_items(entry["bullets"]), 4),
                    "  </ul>",
                    "</div>",
                ]
            )
        )
    return "\n".join(blocks)


def render_education_entries(entries: list[dict]) -> str:
    blocks = []
    for entry in entries:
        meta = entry["years"]
        if entry.get("location"):
            meta = f"{entry['location']} - {meta}"
        block = [
            '<div class="resume-entry">',
            '  <div class="entry-header">',
            f"    <h3>{escape_html(entry['school'])}</h3>",
            f'    <p class="post-meta">{escape_html(meta)}</p>',
            "  </div>",
            f'  <p class="entry-subtitle">{escape_html(entry["degree"])}</p>',
        ]
        if entry.get("minor"):
            block.append(f'  <p>{escape_html(entry["minor"])}</p>')
        block.append("</div>")
        blocks.append("\n".join(block))
    return "\n".join(blocks)


def render_skill_groups(groups: list[dict]) -> str:
    blocks = []
    for group in groups:
        items = group["items"]
        value = ", ".join(items) if isinstance(items, list) else items
        blocks.append(
            "\n".join(
                [
                    '<div class="resume-entry skill-entry">',
                    f'  <p class="entry-subtitle">{escape_html(group["label"])}</p>',
                    f"  <p>{escape_html(value)}</p>",
                    "</div>",
                ]
            )
        )
    return "\n".join(blocks)


def render_publications(items: list[str | dict]) -> str:
    if not items:
        return ""
    publication_items = []
    for item in items:
        if isinstance(item, str):
            publication_items.append(f"<li>{escape_html(item)}</li>")
            continue

        label = escape_html(item["label"])
        if item.get("href"):
            label = (
                f'<a href="{escape_attr(item["href"])}"'
                f'{render_link_attrs(item, default_class="underlined-link")}>'
                f"{label}</a>"
            )
        publication_items.append(f"<li>{label}</li>")

    return "\n".join(
        [
            '<div class="resume-entry">',
            '  <ul class="simple-list">',
            indent_block("\n".join(publication_items), 4),
            "  </ul>",
            "</div>",
        ]
    )


def render_resume_section(heading: str, content_html: str) -> str:
    if not content_html.strip():
        return ""
    return "\n".join(
        [
            '        <section class="content-section reveal">',
            f"          <h2>{escape_html(heading)}</h2>",
            indent_block(content_html, 8),
            "        </section>",
        ]
    )


def render_post_content(blocks: list[dict], heading_items: list[dict]) -> str:
    lines = []
    heading_iter = iter(heading_items)
    for block in blocks:
        block_type = block["type"]
        if block_type == "paragraph":
            lines.append("<p>")
            lines.append(f"  {escape_html(block['text'])}")
            lines.append("</p>")
        elif block_type == "heading":
            heading = next(heading_iter)
            heading_text = escape_html(block["text"])
            if heading["type"] == "part":
                lines.append(
                    f'<h2 class="part-heading" id="{escape_attr(heading["id"])}">{heading_text}</h2>'
                )
            else:
                lines.append(
                    f'<h3 class="post-subheading" id="{escape_attr(heading["id"])}">{heading_text}</h3>'
                )
        elif block_type == "list":
            lines.append('<ul class="simple-list">')
            lines.append(indent_block(render_list_items(block["items"]), 2))
            lines.append("</ul>")
        elif block_type == "link_list":
            lines.append(render_post_link_list(block["items"]))
        elif block_type == "code":
            lines.append(f"<pre><code>{escape_html(block['text'])}</code></pre>")
        elif block_type == "visual":
            lines.append(render_post_visual(block))
        elif block_type == "image":
            lines.append(render_post_image(block))
        else:
            raise ValueError(f"Unsupported post block type: {block_type}")
    return "\n".join(lines)


def build_post_headings(blocks: list[dict]) -> list[dict]:
    headings = []
    used_ids: dict[str, int] = {}
    for block in blocks:
        if block["type"] != "heading":
            continue
        text = block["text"]
        heading_type = "part" if block.get("level") == "part" else "subheading"
        headings.append(
            {
                "text": text,
                "type": heading_type,
                "id": make_heading_id(text, used_ids),
            }
        )
    return headings


def render_post_toc(heading_items: list[dict]) -> str:
    if not heading_items:
        return ""

    lines = [
        '<aside class="post-toc-shell reveal">',
        '  <nav class="post-toc" aria-label="Table of contents">',
        '    <p class="post-toc-label">On this page</p>',
        '    <ul class="post-toc-list">',
    ]

    current_part_open = False
    nested_open = False
    for heading in heading_items:
        href = f'#{escape_attr(heading["id"])}'
        label = escape_html(heading["text"])

        if heading["type"] == "part":
            if nested_open:
                lines.append("    </ul>")
                nested_open = False
            if current_part_open:
                lines.append("    </li>")
            lines.append('    <li class="post-toc-group">')
            lines.append(f'      <a href="{href}" data-toc-type="part">{label}</a>')
            current_part_open = True
        else:
            if not current_part_open:
                lines.append('    <li class="post-toc-group">')
                current_part_open = True
            if not nested_open:
                lines.append('      <ul class="post-toc-sublist">')
                nested_open = True
            lines.append(
                f'        <li><a href="{href}" data-toc-type="subheading">{label}</a></li>'
            )

    if nested_open:
        lines.append("      </ul>")
    if current_part_open:
        lines.append("    </li>")
    lines.append("    </ul>")
    lines.append("  </nav>")
    lines.append("</aside>")
    return "\n".join(lines)


def render_post_image(block: dict) -> str:
    src = block["src"]
    preview_src = src

    if src.endswith(".excalidraw"):
        # Browsers cannot render raw Excalidraw JSON in an <img>, so use a
        # sibling SVG export as the visual preview while keeping the source
        # asset editable in content.
        preview_src = f"{src[:-11]}.svg"

    figure = [
        '<figure class="post-figure">',
        (
            f'  <img src="{escape_attr(preview_src)}" '
            f'alt="{escape_attr(block.get("alt", ""))}" loading="lazy" />'
        ),
    ]
    if block.get("caption"):
        figure.append(f'  <figcaption>{escape_html(block["caption"])}</figcaption>')
    figure.append("</figure>")
    return "\n".join(figure)


def render_post_link_list(items: list[dict]) -> str:
    entries = []
    for item in items:
        label = escape_html(item.get("label", item["href"]))
        entries.append(
            f'<li><a href="{escape_attr(item["href"])}"'
            f'{render_link_attrs(item, default_class="underlined-link")}>{label}</a></li>'
        )

    return "\n".join(
        [
            '<ul class="simple-list">',
            indent_block("\n".join(entries), 2),
            "</ul>",
        ]
    )


def render_post_visual(block: dict) -> str:
    variant = block["variant"]
    classes = f'post-visual post-visual--{escape_attr(variant)}'
    lines = [f'<div class="{classes}">']

    if block.get("title"):
        lines.append(f'  <p class="post-visual-title">{escape_html(block["title"])}</p>')

    if variant == "mono":
        lines.append('  <div class="visual-mono-card">')
        lines.append(f'    <span class="visual-mono-text">{escape_html(block["text"])}</span>')
        lines.append("  </div>")
    elif variant == "token_row":
        lines.append('  <div class="visual-token-row">')
        lines.append('    <div class="visual-token-chips">')
        for token in block["tokens"]:
            lines.append(f'      <span class="visual-token-chip">{escape_html(str(token))}</span>')
        lines.append("    </div>")
        lines.append("  </div>")
    elif variant == "sequence":
        lines.append('  <div class="visual-sequence">')
        for index, row in enumerate(block["rows"], start=1):
            lines.extend(
                [
                    '    <div class="visual-sequence-row">',
                    f'      <span class="visual-sequence-index">{index:02d}</span>',
                    f'      <span class="visual-sequence-text">{escape_html(row)}</span>',
                    "    </div>",
                ]
            )
        lines.append("  </div>")
    elif variant == "pages":
        lines.append('  <div class="visual-page-grid">')
        for item in block["items"]:
            lines.extend(
                [
                    '    <div class="visual-page-card">',
                    f'      <span class="visual-page-name">{escape_html(item["page"])}</span>',
                    f'      <span class="visual-page-owner">{escape_html(item["owner"])}</span>',
                    "    </div>",
                ]
            )
        lines.append("  </div>")
    else:
        raise ValueError(f"Unsupported visual variant: {variant}")

    lines.append("</div>")
    return "\n".join(lines)


def render_footer(site_name: str, *, include_copy: bool) -> str:
    if include_copy:
        text = f"&copy; <span id=\"year\"></span> {escape_html(site_name)}"
    else:
        text = f"<span id=\"year\"></span> {escape_html(site_name)}."
    return (
        "      <footer class=\"site-footer\">\n"
        f"        <p>{text}</p>\n"
        "      </footer>"
    )


def post_meta(post: dict) -> str:
    return ", ".join(post["tags"])


def post_href(post: dict) -> str:
    return f"blog/{post['slug']}/"


def post_output_path(post: dict) -> Path:
    return BLOG_DIR / post["slug"] / "index.html"


def route_output_path(route: str) -> Path:
    return ROOT / route / "index.html"


def make_heading_id(text: str, used_ids: dict[str, int]) -> str:
    base = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    if not base:
        base = "section"

    count = used_ids.get(base, 0)
    used_ids[base] = count + 1
    if count == 0:
        return base
    return f"{base}-{count + 1}"


def slugify(value: str) -> str:
    return value.lower().replace(" ", "-")


def indent_block(text: str, spaces: int) -> str:
    prefix = " " * spaces
    return "\n".join(prefix + line if line else "" for line in text.splitlines())


def escape_html(value: str) -> str:
    return escape(value, quote=False)


def escape_attr(value: str) -> str:
    return escape(value, quote=True)


def write_page(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f"{content}\n", encoding="utf-8")


if __name__ == "__main__":
    main()
